// File: content/experience-data.ts

import { TimelineItem } from "@/types/experience";

export const experienceData: TimelineItem[] = [
  {
    id: "startahb",
    category: "Experience",
    role: "Java Backend Intern",
    organization: "StartAhb Technology Private Limited",
    duration: "25 Jun 2026 — 25 Dec 2026",
    status: "Ongoing",
    shortDescription:
      "Currently working on backend development and testing for software applications, with a primary focus on Java-based backend systems and CRM product development.",
    details: [
      "Develop and maintain backend functionality using Java.",
      "Write clean, maintainable and efficient code.",
      "Develop and integrate backend services.",
      "Test backend functionality and identify issues.",
      "Debug and optimize existing implementations.",
      "Work with scalable, service-based and microservices-oriented architecture.",
      "Contribute to reducing operational/technical cost through efficient backend development.",
      "Contribute to CRM (Customer Relationship Management) product development.",
    ],
    technologies: [
      "Java",
      "Spring Boot",
      "Microservices",
      "Apache Kafka",
      "REST APIs",
      "Git",
      "GitHub",
    ],
    skills: [
      "Backend Development",
      "API Development",
      "Debugging",
      "Testing",
      "Scalability",
      "Code Optimization",
      "Problem Solving",
      "Software Engineering",
    ],
  },
  {
    id: "pantech",
    category: "Experience",
    role: "MERN Stack Intern",
    organization: "Pantech.AI",
    duration: "3 Months",
    shortDescription:
      "Worked with the MERN stack and gained practical experience in full-stack web development workflows.",
    details: [
      "Worked on MERN stack based applications.",
      "Developed and worked with frontend components.",
      "Worked with backend services and APIs.",
      "Integrated frontend and backend functionality.",
      "Worked with database operations.",
      "Debugged and improved application functionality.",
    ],
    technologies: [
      "MongoDB",
      "Express.js",
      "React.js",
      "Node.js",
      "JavaScript",
      "REST APIs",
      "MERN Stack",
    ],
    skills: [
      "Full-Stack Development",
      "JavaScript",
      "API Integration",
      "Database Interaction",
      "Frontend Development",
      "Backend Development",
      "Debugging",
    ],
  },
  {
    id: "cybrom",
    category: "Experience",
    role: "MERN Stack Intern",
    organization: "Cybrom Technology",
    duration: "10 Jan 2026 — 25 Jan 2026",
    shortDescription:
      "Gained practical exposure to MERN stack development and modern web application development workflows.",
    details: [
      "Worked with the MERN technology stack.",
      "Learned and practiced full-stack web development.",
      "Worked with frontend and backend concepts.",
      "Gained exposure to REST API based application development.",
      "Worked with database integration concepts.",
      "Improved understanding of modern web application architecture.",
    ],
    technologies: [
      "MongoDB",
      "Express.js",
      "React.js",
      "Node.js",
      "JavaScript",
      "REST APIs",
    ],
    skills: [
      "Web Development",
      "Full-Stack Development",
      "JavaScript",
      "API Development",
      "Database Integration",
      "Problem Solving",
    ],
  },
  {
    id: "oist",
    category: "Education",
    role: "B.Tech — Information Technology",
    organization: "Oriental Institute of Science and Technology (OIST)",
    duration: "2024 — 2028 (Expected)",
    status: "5th Semester",
    cgpa: "7.33",
    isEducationAnchor: true, // This marks exactly where the navbar will scroll for "Education"
    shortDescription:
      "Currently pursuing B.Tech in Information Technology with a focus on software development and backend engineering. Gaining practical exposure through internships, projects, hackathons, and entrepreneurship.",
    technologies: [
      "Java",
      "Data Structures & Algorithms",
      "Object-Oriented Programming",
      "Database Management Systems",
      "Web Development",
      "Spring Boot",
      "Software Development",
    ],
  },
  {
    id: "velvet-dusk",
    category: "Entrepreneurship",
    role: "Co-Founder",
    organization: "Velvet Dusk Perfume",
    duration: "~1 Year",
    shortDescription:
      "Started and worked on my own perfume brand, gaining practical experience beyond software development.",
    details: [
      "Marketing, sales, and brand promotion.",
      "Customer communication and relationship handling.",
      "Social media and product promotion.",
      "Understanding customer requirements and business communication.",
      "Day-to-day business activities and brand building.",
    ],
    skills: [
      "Entrepreneurship",
      "Marketing",
      "Sales",
      "Communication",
      "Customer Handling",
      "Leadership",
      "Negotiation",
      "Brand Building",
      "Ownership",
    ],
  },
  {
    id: "nss",
    category: "Leadership",
    role: "Volunteer",
    organization: "NSS",
    duration: "Active",
    shortDescription:
      "Participated in community and volunteer activities as part of NSS.",
    skills: [
      "Teamwork",
      "Community engagement",
      "Communication",
      "Responsibility",
      "Collaboration",
      "Social awareness",
      "Event participation",
    ],
  },
  {
    id: "hackathons",
    category: "Leadership",
    role: "Participant / Event Involvement",
    organization: "Hackathons & Technical Events",
    duration: "Ongoing",
    shortDescription:
      "Participated in hackathons and technical events, gaining practical exposure to collaborative problem solving and rapid development.",
    skills: [
      "Problem Solving",
      "Team Collaboration",
      "Rapid Learning",
      "Technical Experimentation",
      "Idea Development",
      "Presentation",
      "Working Under Time Constraints",
      "Adaptability",
      "Debugging",
    ],
  },
];
